### PR TITLE
Change sidebar for desktop

### PR DESCRIPTION
**Pull request by TheComputerM**

### CODE REVIEW

**Comment by TheComputerM** [comment]
@zeeshanok ;
- We currently have no plans for a 'user' page, everything will be in settings, we can add it later if there is a need
- Why are you not using the flutter navigation rail? Is there any problem with it?
- There is currently no indicator of which page is active.

**Comment by zeeshanok** [comment]
@TheComputerM
- The user avatar button has been reverted to the theme switcher button.
- The built-in navigation rail that flutter provides does not give enough customization to fit the design. 
  - The default navigation rail buttons don't have enough spacing between each other.
  - The design requires that a tooltip appears next to the nav button on hover, which does not exist for the default nav rail.
- The selected page can now be seen.

**Review by zeeshanok — CHANGES_REQUESTED** [review]
By convention, a function that builds and returns the app's theme is usually placed in the `main.dart` file or a separate theme file. In this case, placing it here would make it so that in the future it will add clutter to `main.dart` when the theme requires custom colours and lots of general changes. At the same time, I feel the function should not be in `providers/theme.dart` but in another `theme.dart` file next to `main.dart`.

**Comment by TheComputerM** [comment]
> By convention, a function that builds and returns the app's theme is usually placed in the `main.dart` file or a separate theme file. In this case, placing it here would make it so that in the future it will add clutter to `main.dart` when the theme requires custom colours and lots of general changes. At the same time, I feel the function should not be in `providers/theme.dart` but in another `theme.dart` file next to `main.dart`.

Ok then, when the theme is kinda finalized, create a `theme.dart` next to main.dart

**Pull request merged**
